// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCYdiujozoEPhZpVwiEt3PY7p0rifO7s',
    appId: '1:165903390131:web:fe365bdbb734b82e69a7c6',
    messagingSenderId: '165903390131',
    projectId: 'bfla2023-67468',
    authDomain: 'bfla2023-67468.firebaseapp.com',
    storageBucket: 'bfla2023-67468.appspot.com',
    measurementId: 'G-RJH42MMWGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuoFS4YS89_OEo59VzN3E0cNXDYMlMC4',
    appId: '1:165903390131:android:e73e22c0b1a3520769a7c6',
    messagingSenderId: '165903390131',
    projectId: 'bfla2023-67468',
    storageBucket: 'bfla2023-67468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKteULZBMnGaEavAvoZHYB7L9qQEJqBM',
    appId: '1:165903390131:ios:7b97f2390c85f38d69a7c6',
    messagingSenderId: '165903390131',
    projectId: 'bfla2023-67468',
    storageBucket: 'bfla2023-67468.appspot.com',
    iosClientId: '165903390131-fn0no8hj2hth3921gsv0ul8gqo62hhki.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMedBase2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKteULZBMnGaEavAvoZHYB7L9qQEJqBM',
    appId: '1:165903390131:ios:8515014add3cc0ee69a7c6',
    messagingSenderId: '165903390131',
    projectId: 'bfla2023-67468',
    storageBucket: 'bfla2023-67468.appspot.com',
    iosClientId: '165903390131-r3bcs0c1a47pfkflpnq766an97j7fk3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMedBase2023.RunnerTests',
  );
}
